use bedrock::level::settings;
use chrono::{TimeZone, Utc};

fn get_last_played() -> i64 {
    let launch_date = Utc.with_ymd_and_hms(2015, 7, 29, 0, 0, 0).unwrap();
    let current_date = Utc::now();
    let duration = current_date.signed_duration_since(launch_date);

    duration.num_seconds().swap_bytes()
}

pub fn default_settings() -> settings::LevelSettings {
    settings::LevelSettings {
        file_version: 10,
        editor_world_type: 0,
        created_in_editor: false,
        exported_from_editor: false,
        random_seed_allowed: false,
        sleeping_percentage: 100,
        recipes_unlock: true,
        cheats_enabled: true,
        lightning_level: 0.0,
        lightning_time: 7220,
        rain_level: 0.0,
        rain_time: 7220,
        difficulty: 2,
        game_mode: 1,
        generator: 2,
        limited_world_origin_x: 0,
        limited_world_origin_y: 32767,
        limited_world_origin_z: 0,
        limited_world_depth: 16,
        limited_world_width: 16,
        minimum_compatible_client_version: [1, 26, 40, 0, 0],
        nether_scale: 8,
        network_version: 975,
        platform: 2,
        platform_broadcast_intent: 2,
        random_seed: 0,
        spawn_v1_villagers: false,
        spawn_x: 0,
        spawn_y: 32767,
        spawn_z: 0,
        storage_version: 10,
        time: 6000,
        world_version: 1,
        xbox_broadcast_intent: 2,
        current_tick: 0,
        experiments: settings::Experiments {
            experiments_ever_used: false,
            saved_with_toggled_experiments: false,
        },
        abilities: settings::Abilities {
            attack_mobs: true,
            attack_players: true,
            build: true,
            doors_and_switches: true,
            flying: false,
            instant_build: false,
            invulnerable: false,
            lightning: false,
            mayfly: false,
            mine: true,
            op: false,
            open_containers: true,
            teleport: false,
            fly_speed: 0.05,
            vertical_fly_speed: 1.0,
            walk_speed: 0.1,
        },
        edu_offer: 0,
        education_features_enabled: false,
        last_opened_with_version: [1, 26, 40, 5, 0],
        bonus_chest_enabled: false,
        bonus_chest_spawned: false,
        command_block_output: true,
        center_maps_to_origin: false,
        command_blocks_enabled: true,
        commands_enabled: true,
        confirmed_platform_locked_content: false,
        daylight_cycle: 1,
        daylight_lock: false,
        limited_crafting: false,
        entity_drops: true,
        fire_tick: true,
        immediate_respawn: false,
        insomnia: true,
        mob_loot: true,
        mob_spawning: true,
        tile_drops: true,
        weather_cycle: false,
        drowning_damage: true,
        fall_damage: true,
        fire_damage: true,
        freeze_damage: true,
        keep_inventory: false,
        max_command_chain_length: 65535,
        mob_griefing: true,
        natural_regeneration: true,
        function_command_limit: 10000,
        pvp: true,
        random_tick_speed: 0,
        respawn_blocks_explode: true,
        send_command_feedback: true,
        show_border_effect: true,
        show_coordinates: true,
        show_death_messages: true,
        show_tags: true,
        spawn_radius: 24,
        tnt_explodes: true,
        force_game_mode: false,
        has_been_loaded_in_creative: true,
        has_locked_behavior_pack: false,
        has_locked_resource_pack: false,
        immutable_world: false,
        is_from_locked_template: false,
        is_from_world_template: false,
        is_single_use_world: false,
        is_world_template_option_locked: false,
        requires_copied_pack_removal_check: false,
        texture_packs_required: false,
        lan_broadcast: true,
        lan_broadcast_intent: 1,
        multiplayer_game: true,
        multiplayer_game_intent: 1,
        last_played: get_last_played(),
        base_game_version: "*".to_string(),
        biome_override: String::new(),
        flat_world_layers:
            "{\"biome_id\":1,\"encoding_version\":6,\"preset_id\":\"TheVoid\",\"world_version\":\"version.post_1_18\"}"
                .to_string(),
        inventory_version: "1.26.21".to_string(),
        level_name: String::new(),
        use_msa_gamertags_only: false,
        world_start_count: 0,
        start_with_map_enabled: false,
        spawn_mobs: true,
        server_chunk_tick_range: 4,
        permissions_level: 0,
        player_permissions_level: 1,
        prid: String::new(),
        world_policies: settings::Policies {},
        has_uncomplete_world_file_on_disk: false,
        is_hardcore: false,
        player_has_died: false,
        allow_anonymous_block_drops_in_editor_worlds: false,
        player_waypoints: 1,
        projectiles_can_break_blocks: true,
        server_editor_connection_policy: 0,
        show_days_played: false,
        show_recipe_messages: true,
        tnt_explosion_drop_decay: false,
    }
}
