[package]
name = "world"
version.workspace = true
edition = "2024"

[dependencies]

clap = { workspace = true }
include_dir = { workspace = true }
filetime = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
bedrock = { git = "https://github.com/bedrock-crustaceans/bedrock-rs.git", features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
